/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#414753",
        "on-background": "#0d1c2e",
        "inverse-primary": "#aac7ff",
        "on-secondary": "#ffffff",
        "outline": "#727784",
        "surface-tint": "#005cba",
        "primary-fixed-dim": "#aac7ff",
        "inverse-surface": "#233144",
        "secondary-container": "#da3433",
        "outline-variant": "#c1c6d5",
        "primary": "#004e9f",
        "surface-container": "#e6eeff",
        "on-secondary-fixed-variant": "#930010",
        "tertiary": "#025e16",
        "surface": "#f8f9ff",
        "secondary-fixed-dim": "#ffb3ac",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#fffbff",
        "on-primary-container": "#dfe8ff",
        "surface-dim": "#ccdbf3",
        "surface-variant": "#d5e3fc",
        "on-tertiary-fixed-variant": "#005312",
        "primary-container": "#0066cc",
        "background": "#f8f9ff",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#002204",
        "secondary": "#b6171e",
        "surface-container-high": "#dce9ff",
        "tertiary-fixed-dim": "#88d982",
        "primary-fixed": "#d7e3ff",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#a8fca1",
        "tertiary-fixed": "#a3f69c",
        "inverse-on-surface": "#eaf1ff",
        "tertiary-container": "#28772d",
        "surface-container-highest": "#d5e3fc",
        "on-surface": "#0d1c2e",
        "on-error-container": "#93000a",
        "surface-container-low": "#eff4ff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#00458e",
        "on-secondary-fixed": "#410003",
        "secondary-fixed": "#ffdad6",
        "on-error": "#ffffff",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed": "#001b3e"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "16px",
        "unit": "4px",
        "margin-page": "20px",
        "sidebar-width": "220px",
        "container-max": "1360px"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
