package com.aura.auth.service;
import com.aura.auth.dto.*; import com.aura.auth.exception.AuthException; import com.aura.auth.security.*; import com.aura.common.response.ErrorCode; import com.aura.role.enums.RoleName; import com.aura.role.repository.RoleRepository; import com.aura.user.entity.*; import com.aura.user.repository.*; import java.util.*; import org.springframework.security.authentication.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import org.springframework.security.core.AuthenticationException;
@Service public class AuthService{
 private final UserRepository users;private final RoleRepository roles;private final UserRoleRepository userRoles;private final PasswordEncoder encoder;private final AuthenticationManager auth;private final JwtTokenProvider jwt;private final RefreshTokenService refresh;
 public AuthService(UserRepository u,RoleRepository r,UserRoleRepository ur,PasswordEncoder e,AuthenticationManager a,JwtTokenProvider j,RefreshTokenService f){users=u;roles=r;userRoles=ur;encoder=e;auth=a;jwt=j;refresh=f;}
 @Transactional public UserResponse register(RegisterRequest q){String email=q.email().trim().toLowerCase(Locale.ROOT);if(users.existsByEmailIgnoreCase(email))throw new AuthException(ErrorCode.EMAIL_ALREADY_EXISTS,"Email đã được sử dụng");var u=users.save(new User(email,encoder.encode(q.password()),q.fullName()==null?null:q.fullName().trim()));var role=roles.findByName(RoleName.USER).orElseThrow();userRoles.save(new UserRole(u,role));return view(u,List.of("USER"));}
 public LoginResult login(LoginRequest q){String email=q.email().trim().toLowerCase(Locale.ROOT);try{var a=auth.authenticate(new UsernamePasswordAuthenticationToken(email,q.password()));var p=(AuraUserPrincipal)a.getPrincipal();if(!p.enabled())throw new AuthException(ErrorCode.ACCOUNT_DISABLED,"Tài khoản đã bị vô hiệu hóa");var u=users.findById(p.id()).orElseThrow();return result(u,p.roles());}catch(DisabledException e){throw new AuthException(ErrorCode.ACCOUNT_DISABLED,"Tài khoản đã bị vô hiệu hóa");}catch(AuthenticationException e){throw new AuthException(ErrorCode.INVALID_CREDENTIALS,"Email hoặc mật khẩu không chính xác");}}
 public LoginResult refresh(String raw){var r=refresh.rotate(raw);var names=userRoles.findAllByUserId(r.user().getId()).stream().map(x->x.getRole().getName().name()).toList();return result(r.user(),names,r.issued());}
 public void logout(String raw){if(raw!=null)refresh.revoke(raw);}
 public UserResponse me(AuraUserPrincipal p){var u=users.findById(p.id()).orElseThrow();return view(u,p.roles());}
 private LoginResult result(com.aura.user.entity.User u,List<String> names){return result(u,names,refresh.issue(u));}
 private LoginResult result(com.aura.user.entity.User u,List<String> names,RefreshTokenService.Issued issued){return new LoginResult(new LoginResponse(jwt.create(u.getId(),names),"Bearer",jwt.expiresIn(),view(u,names)),issued.raw());}
 private UserResponse view(com.aura.user.entity.User u,List<String> names){return new UserResponse(u.getId(),u.getEmail(),u.getFullName(),names,u.isActive());}
 public record LoginResult(LoginResponse response,String refreshToken){}
}
