CREATE TABLE roles (id BIGSERIAL PRIMARY KEY, name VARCHAR(30) NOT NULL UNIQUE);
CREATE TABLE users (id UUID PRIMARY KEY, email VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE user_roles (user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, role_id BIGINT NOT NULL REFERENCES roles(id), PRIMARY KEY (user_id, role_id));
INSERT INTO roles(name) VALUES ('USER'), ('DOCTOR'), ('CLINIC'), ('ADMIN');
