package com.aura.feedback.dto;

import java.time.Instant;
import java.util.UUID;

/**
 * HIPAA NFR-10 / NFR-11 Compliant De-Identified Retraining Dataset Item.
 * Strips all Direct Identifiers (Real Name, Real MRN, Phone, Address),
 * replacing them with HMAC-SHA256 Pseudonyms generated by PatientAnonymizerService.
 */
public record RetrainingDatasetItemDto(
    UUID feedbackId,
    UUID screeningId,
    String pseudonymId,
    String deidentifiedMrn,
    Integer age,
    String gender,
    Integer systolicBp,
    Integer diastolicBp,
    Double hba1c,
    Boolean hasDiabetes,
    Boolean hasHypertension,
    String aiRiskLevel,
    String doctorRiskLevel,
    Boolean isAccurate,
    String feedbackNotes,
    String vesselAnnotationData,
    Instant exportedAt
) {}
