package com.aura.common.response;

public enum ErrorCode {
  VALIDATION_ERROR,
  INVALID_REQUEST,
  RESOURCE_NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  EMAIL_ALREADY_EXISTS,
  INVALID_CREDENTIALS,
  ACCOUNT_DISABLED,
  UNAUTHORIZED,
  ACCESS_DENIED,
  INVALID_TOKEN,
  TOKEN_EXPIRED,
  REFRESH_TOKEN_INVALID,
  REFRESH_TOKEN_REVOKED
}
